batching_timeout = 5 #默认的凑batch的超时时间
precision="fp16"

[jpg_decoder]
backend = "Sequential[DecodeTensor,cvtColorTensor,ResizePadTensor,SyncTensor]"
color = "bgr"
instance_num = 5
max_h = 416
max_w = 416

next = "detect"
[detect]
# 静态batch， max默认为1
backend = "SyncTensor[TensorrtTensor]" 
batching_timeout = 5 #默认的凑batch的超时时间
instance_num = 2 
max = 4 
model = "../../../examples/yolox/yolox_tiny.onnx" 
"model::cache" = "./yolox_tiny.trt" 
next = "remove_extra_key" 
postprocessor = "BatchingPostProcYolox_45_30" 

[remove_extra_key]
map = "detect[result:data]"
